language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  api_key:
    secure: J4yCNHtnfHbdaYe2HF6dELIhVmn4mnDVYj/TNH+tZbgYN1uoz1j7I2RF66XvI+4N0W4v1O3UjrZITb0QVxaz7+0zDryJzuTgMjrIgkDTfl1JDzJSXrLy8bkTZOUYlPBn6Vs7Xk9XWNd16vCSifTxmAuFds8NNk1cfiqS4Mb7lV0VUA39vBaeHevVMgaZs5JBl7cgEiwVACaPk8VX6Z6GLgRiSICFp9TI5VNb+lzYINzOCUjffzeZn2BktKqkGHye9FIBzMq989NQNG8r+tWa2DONujrRfjcWk8cHWAsmT3NtOOFNsURHiu7NMS8Aezs74TulBmSPHCMF1+0iTHVSDsberYp0e2ZyHmpGUQBEEDBG9koIbUAEw2aF8iCfHW+5S4iiBi5v0rOZIqVuQDLHts4zhntWjHr2f1Y47d9cLutKlqbNPkr6qNV3Tmcd2+S4lKHhwD08Ah/G7agNwynSS6A0A2V7F3PIhIYrMkOJ0WLfviqZmpEy6fQH3Z4prANlMorZa8CdEarrikN4vS6zlbZRQVoLtXjJ1K7FPeGWobOFWvwAW6dp06s4Hf4hJk+tJ9fP+zlk5G5B8MHyYRfu6b+ZRJpOkF8QtnwULcD9ATaqy2Ve7scl1zEZnMLT6GHPcrdiMlY7pGhosxGtiN7YWzn415G9f3Ynv/l4X9AyslE=
